name: PostgreSQL service example
on: push
jobs:
  # label of the container job
  postgres-job:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest


    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Run psql from cli
        run: sudo -u postgres psql -c 'SELECT version();'

      - name: execute script
        run: |
          chmod +x "./sample.sh"
          sudo -u postgres "./sample.sh"
        shell: bash