name: PostgreSQL service example
on: push
jobs:
  plpgsql-check-job:
    name: plpgsql-check-job
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: pgTap installation
        run: |
          git clone https://github.com/theory/pgtap
          cd pgtap
          sudo -u postgres -c "sudo make && sudo make install && sudo make installcheck"
          echo "###########################"
          psql -U postgres -c 'CREATE EXTENSION pgtap;'
