name: PostgreSQL service example
on: push
jobs:
  plpgsql-check-job:
    name: plpgsql-check-job
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: pgTap installation
        run: |
          sudo -u postgres "./install_pgtap.sh"
          echo "###########################"
          psql -U postgres -c 'CREATE EXTENSION pgtap;'
