name: PostgreSQL service example
on: push
jobs:
  plpgsql-check-job:
    name: plpgsql-check-job
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install PL/pgSQL Check Extension
        run: |
          chmod +x "./install_plpgsql_check.sh"
          "./install_plpgsql_check.sh"
        shell: bash

      - name: Install csv2md
        run: |
          pip install csv2md

      - name: Execute script
        id: execute
        run: |
          chmod +x "./sample.sh"
          sudo -u postgres "./sample.sh"
        shell: bash

      - name: export PL/pgSQL Check report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: plpgsql_check_result
          path: /tmp/all_fun_plpgsql_check.csv

      - name: PL/pgSQL Check
        uses: LouisBrunner/checks-action@v1.2.0
        if: ${{ always() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PL/pgSQL Check
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{steps.execute.outputs.plpgsql_check_summary}}}
          output_text_description_file: /tmp/all_fun_plpgsql_check.md
