name: PostgreSQL service example
on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest


    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: demo GH Checks
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Based On Job
          conclusion: ${{ job.status }}

      - name: demo GH Checks 2
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Based On Job2
          conclusion: failure
      
      # - name: Install PL/pgSQL Check Extension
      #   run: |
      #     chmod +x "./install_plpgsql_check.sh"
      #     "./install_plpgsql_check.sh"
      #   shell: bash

      # - name: execute script
      #   run: |
      #     chmod +x "./sample.sh"
      #     sudo -u postgres "./sample.sh"
      #   shell: bash
      
      # - name: export PL/pgSQL Check report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: plpgsql_check_result
      #     path: /tmp/plpgsql_check_result.txt