name: PostgreSQL service example
on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest


    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
        
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check PG PS
        run: ps -ef |grep postgres
        
      - name: Check pg_restore location
        run: sudo -u postgres -c "which pg_restore"

      
      - name: execute script
        run: |
          chmod +x "./sample.sh"
          sudo -u postgres "./sample.sh"
        shell: bash