name: Manual Workflow Testing
on: workflow_dispatch
permissions:
  issues: write
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue in Remote Repo
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          owner: Akil1470
          repo: test
          title: Sample Test Issue
          body: Test Body of Issue
