name: Manual Workflow Testing
on: workflow_dispatch
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue in Remote Repo
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          repo: mops-db-row-count
          title: Sample Test Issue
          body: Test Body of Issue
